# Generated by Django 5.0.4 on 2024-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='username',
        ),
    ]
