# Generated by Django 5.0.4 on 2024-05-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
